version: "3"

tasks:
  tidy:
    cmds:
      - go mod tidy
  gen:
    cmds:
      - go generate ./ent
  run:
    cmds:
      - go mod tidy
      - reflex -g 'cmd/kala.go' -s go run ./cmd/kala.go
  reflex:
    cmds:
      - reflex -d none -g 'ent/schema/*.go' -s task gen
  describe:
    cmds:
      - ent describe ./ent/schema > schema_desc.txt && code schema_desc.txt
