version: "3"

tasks:
  tidy:
    cmds:
      - go mod tidy
  gen:
    cmds:
      - go generate ./ent
  run:
    cmds:
      - go mod tidy
      - reflex -s go run ./cmd/kala.go
  run-once:
    cmds:
      - go mod tidy
      - go run ./cmd/kala.go
  test:
    cmds:
      - go test $(go list ./... | grep -v '/kala-go/ent')
  tree:
    cmds:
      - go mod tidy
      - reflex -g 'tree/tree.go' -s go run ./tree/tree.go
  reflex:
    cmds:
      - reflex -d none -g 'ent/schema/*.go' -s task gen
  describe:
    cmds:
      - ent describe ./ent/schema > schema_desc.txt && code schema_desc.txt
