// Code generated by entc, DO NOT EDIT.

package relation

const (
	// Label holds the string label denoting the relation type in the database.
	Label = "relation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// EdgeTypeconfig holds the string denoting the typeconfig edge name in mutations.
	EdgeTypeconfig = "typeconfig"
	// EdgeRelTypeconfigs holds the string denoting the rel_typeconfigs edge name in mutations.
	EdgeRelTypeconfigs = "rel_typeconfigs"
	// EdgePermissions holds the string denoting the permissions edge name in mutations.
	EdgePermissions = "permissions"
	// EdgeTuples holds the string denoting the tuples edge name in mutations.
	EdgeTuples = "tuples"
	// Table holds the table name of the relation in the database.
	Table = "relations"
	// TypeconfigTable is the table that holds the typeconfig relation/edge.
	TypeconfigTable = "relations"
	// TypeconfigInverseTable is the table name for the TypeConfig entity.
	// It exists in this package in order to avoid circular dependency with the "typeconfig" package.
	TypeconfigInverseTable = "type_configs"
	// TypeconfigColumn is the table column denoting the typeconfig relation/edge.
	TypeconfigColumn = "type_config_relations"
	// RelTypeconfigsTable is the table that holds the rel_typeconfigs relation/edge. The primary key declared below.
	RelTypeconfigsTable = "relation_rel_typeconfigs"
	// RelTypeconfigsInverseTable is the table name for the TypeConfig entity.
	// It exists in this package in order to avoid circular dependency with the "typeconfig" package.
	RelTypeconfigsInverseTable = "type_configs"
	// PermissionsTable is the table that holds the permissions relation/edge. The primary key declared below.
	PermissionsTable = "permission_relations"
	// PermissionsInverseTable is the table name for the Permission entity.
	// It exists in this package in order to avoid circular dependency with the "permission" package.
	PermissionsInverseTable = "permissions"
	// TuplesTable is the table that holds the tuples relation/edge.
	TuplesTable = "tuples"
	// TuplesInverseTable is the table name for the Tuple entity.
	// It exists in this package in order to avoid circular dependency with the "tuple" package.
	TuplesInverseTable = "tuples"
	// TuplesColumn is the table column denoting the tuples relation/edge.
	TuplesColumn = "relation_id"
)

// Columns holds all SQL columns for relation fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldValue,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "relations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"type_config_relations",
}

var (
	// RelTypeconfigsPrimaryKey and RelTypeconfigsColumn2 are the table columns denoting the
	// primary key for the rel_typeconfigs relation (M2M).
	RelTypeconfigsPrimaryKey = []string{"relation_id", "type_config_id"}
	// PermissionsPrimaryKey and PermissionsColumn2 are the table columns denoting the
	// primary key for the permissions relation (M2M).
	PermissionsPrimaryKey = []string{"permission_id", "relation_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
