// Code generated by entc, DO NOT EDIT.

package typeconfig

const (
	// Label holds the string label denoting the typeconfig type in the database.
	Label = "type_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRelations holds the string denoting the relations field in the database.
	FieldRelations = "relations"
	// FieldPermissions holds the string denoting the permissions field in the database.
	FieldPermissions = "permissions"
	// Table holds the table name of the typeconfig in the database.
	Table = "type_configs"
)

// Columns holds all SQL columns for typeconfig fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRelations,
	FieldPermissions,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
