// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/DeluxeOwl/kala-go/ent/predicate"
	"github.com/DeluxeOwl/kala-go/ent/schema"
	"github.com/DeluxeOwl/kala-go/ent/typeconfig"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTypeConfig = "TypeConfig"
)

// TypeConfigMutation represents an operation that mutates the TypeConfig nodes in the graph.
type TypeConfigMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	relations     **schema.Relations
	permissions   **schema.Permissions
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*TypeConfig, error)
	predicates    []predicate.TypeConfig
}

var _ ent.Mutation = (*TypeConfigMutation)(nil)

// typeconfigOption allows management of the mutation configuration using functional options.
type typeconfigOption func(*TypeConfigMutation)

// newTypeConfigMutation creates new mutation for the TypeConfig entity.
func newTypeConfigMutation(c config, op Op, opts ...typeconfigOption) *TypeConfigMutation {
	m := &TypeConfigMutation{
		config:        c,
		op:            op,
		typ:           TypeTypeConfig,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTypeConfigID sets the ID field of the mutation.
func withTypeConfigID(id int) typeconfigOption {
	return func(m *TypeConfigMutation) {
		var (
			err   error
			once  sync.Once
			value *TypeConfig
		)
		m.oldValue = func(ctx context.Context) (*TypeConfig, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TypeConfig.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTypeConfig sets the old TypeConfig of the mutation.
func withTypeConfig(node *TypeConfig) typeconfigOption {
	return func(m *TypeConfigMutation) {
		m.oldValue = func(context.Context) (*TypeConfig, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TypeConfigMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TypeConfigMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TypeConfigMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TypeConfigMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TypeConfig.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *TypeConfigMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TypeConfigMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the TypeConfig entity.
// If the TypeConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TypeConfigMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TypeConfigMutation) ResetName() {
	m.name = nil
}

// SetRelations sets the "relations" field.
func (m *TypeConfigMutation) SetRelations(s *schema.Relations) {
	m.relations = &s
}

// Relations returns the value of the "relations" field in the mutation.
func (m *TypeConfigMutation) Relations() (r *schema.Relations, exists bool) {
	v := m.relations
	if v == nil {
		return
	}
	return *v, true
}

// OldRelations returns the old "relations" field's value of the TypeConfig entity.
// If the TypeConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TypeConfigMutation) OldRelations(ctx context.Context) (v *schema.Relations, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRelations is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRelations requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRelations: %w", err)
	}
	return oldValue.Relations, nil
}

// ResetRelations resets all changes to the "relations" field.
func (m *TypeConfigMutation) ResetRelations() {
	m.relations = nil
}

// SetPermissions sets the "permissions" field.
func (m *TypeConfigMutation) SetPermissions(s *schema.Permissions) {
	m.permissions = &s
}

// Permissions returns the value of the "permissions" field in the mutation.
func (m *TypeConfigMutation) Permissions() (r *schema.Permissions, exists bool) {
	v := m.permissions
	if v == nil {
		return
	}
	return *v, true
}

// OldPermissions returns the old "permissions" field's value of the TypeConfig entity.
// If the TypeConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TypeConfigMutation) OldPermissions(ctx context.Context) (v *schema.Permissions, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPermissions is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPermissions requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPermissions: %w", err)
	}
	return oldValue.Permissions, nil
}

// ResetPermissions resets all changes to the "permissions" field.
func (m *TypeConfigMutation) ResetPermissions() {
	m.permissions = nil
}

// Where appends a list predicates to the TypeConfigMutation builder.
func (m *TypeConfigMutation) Where(ps ...predicate.TypeConfig) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TypeConfigMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (TypeConfig).
func (m *TypeConfigMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TypeConfigMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, typeconfig.FieldName)
	}
	if m.relations != nil {
		fields = append(fields, typeconfig.FieldRelations)
	}
	if m.permissions != nil {
		fields = append(fields, typeconfig.FieldPermissions)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TypeConfigMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case typeconfig.FieldName:
		return m.Name()
	case typeconfig.FieldRelations:
		return m.Relations()
	case typeconfig.FieldPermissions:
		return m.Permissions()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TypeConfigMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case typeconfig.FieldName:
		return m.OldName(ctx)
	case typeconfig.FieldRelations:
		return m.OldRelations(ctx)
	case typeconfig.FieldPermissions:
		return m.OldPermissions(ctx)
	}
	return nil, fmt.Errorf("unknown TypeConfig field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TypeConfigMutation) SetField(name string, value ent.Value) error {
	switch name {
	case typeconfig.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case typeconfig.FieldRelations:
		v, ok := value.(*schema.Relations)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRelations(v)
		return nil
	case typeconfig.FieldPermissions:
		v, ok := value.(*schema.Permissions)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPermissions(v)
		return nil
	}
	return fmt.Errorf("unknown TypeConfig field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TypeConfigMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TypeConfigMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TypeConfigMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TypeConfig numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TypeConfigMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TypeConfigMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TypeConfigMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TypeConfig nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TypeConfigMutation) ResetField(name string) error {
	switch name {
	case typeconfig.FieldName:
		m.ResetName()
		return nil
	case typeconfig.FieldRelations:
		m.ResetRelations()
		return nil
	case typeconfig.FieldPermissions:
		m.ResetPermissions()
		return nil
	}
	return fmt.Errorf("unknown TypeConfig field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TypeConfigMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TypeConfigMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TypeConfigMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TypeConfigMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TypeConfigMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TypeConfigMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TypeConfigMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TypeConfig unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TypeConfigMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TypeConfig edge %s", name)
}
