// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/DeluxeOwl/kala-go/ent/permission"
	"github.com/DeluxeOwl/kala-go/ent/typeconfig"
)

// Permission is the model entity for the Permission schema.
type Permission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PermissionQuery when eager-loading is set.
	Edges                   PermissionEdges `json:"edges"`
	type_config_permissions *int
}

// PermissionEdges holds the relations/edges for other nodes in the graph.
type PermissionEdges struct {
	// Relations holds the value of the relations edge.
	Relations []*Relation `json:"relations,omitempty"`
	// Typeconfig holds the value of the typeconfig edge.
	Typeconfig *TypeConfig `json:"typeconfig,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RelationsOrErr returns the Relations value or an error if the edge
// was not loaded in eager-loading.
func (e PermissionEdges) RelationsOrErr() ([]*Relation, error) {
	if e.loadedTypes[0] {
		return e.Relations, nil
	}
	return nil, &NotLoadedError{edge: "relations"}
}

// TypeconfigOrErr returns the Typeconfig value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PermissionEdges) TypeconfigOrErr() (*TypeConfig, error) {
	if e.loadedTypes[1] {
		if e.Typeconfig == nil {
			// The edge typeconfig was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: typeconfig.Label}
		}
		return e.Typeconfig, nil
	}
	return nil, &NotLoadedError{edge: "typeconfig"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Permission) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case permission.FieldID:
			values[i] = new(sql.NullInt64)
		case permission.FieldName, permission.FieldValue:
			values[i] = new(sql.NullString)
		case permission.ForeignKeys[0]: // type_config_permissions
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Permission", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Permission fields.
func (pe *Permission) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case permission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pe.ID = int(value.Int64)
		case permission.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pe.Name = value.String
			}
		case permission.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				pe.Value = value.String
			}
		case permission.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field type_config_permissions", value)
			} else if value.Valid {
				pe.type_config_permissions = new(int)
				*pe.type_config_permissions = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryRelations queries the "relations" edge of the Permission entity.
func (pe *Permission) QueryRelations() *RelationQuery {
	return (&PermissionClient{config: pe.config}).QueryRelations(pe)
}

// QueryTypeconfig queries the "typeconfig" edge of the Permission entity.
func (pe *Permission) QueryTypeconfig() *TypeConfigQuery {
	return (&PermissionClient{config: pe.config}).QueryTypeconfig(pe)
}

// Update returns a builder for updating this Permission.
// Note that you need to call Permission.Unwrap() before calling this method if this Permission
// was returned from a transaction, and the transaction was committed or rolled back.
func (pe *Permission) Update() *PermissionUpdateOne {
	return (&PermissionClient{config: pe.config}).UpdateOne(pe)
}

// Unwrap unwraps the Permission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pe *Permission) Unwrap() *Permission {
	tx, ok := pe.config.driver.(*txDriver)
	if !ok {
		panic("ent: Permission is not a transactional entity")
	}
	pe.config.driver = tx.drv
	return pe
}

// String implements the fmt.Stringer.
func (pe *Permission) String() string {
	var builder strings.Builder
	builder.WriteString("Permission(")
	builder.WriteString(fmt.Sprintf("id=%v", pe.ID))
	builder.WriteString(", name=")
	builder.WriteString(pe.Name)
	builder.WriteString(", value=")
	builder.WriteString(pe.Value)
	builder.WriteByte(')')
	return builder.String()
}

// Permissions is a parsable slice of Permission.
type Permissions []*Permission

func (pe Permissions) config(cfg config) {
	for _i := range pe {
		pe[_i].config = cfg
	}
}
