// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/DeluxeOwl/kala-go/ent/schema"
	"github.com/DeluxeOwl/kala-go/ent/typeconfig"
)

// TypeConfig is the model entity for the TypeConfig schema.
type TypeConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Relations holds the value of the "relations" field.
	Relations *schema.Relations `json:"relations,omitempty"`
	// Permissions holds the value of the "permissions" field.
	Permissions *schema.Permissions `json:"permissions,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TypeConfig) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case typeconfig.FieldRelations, typeconfig.FieldPermissions:
			values[i] = new([]byte)
		case typeconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case typeconfig.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TypeConfig", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TypeConfig fields.
func (tc *TypeConfig) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case typeconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tc.ID = int(value.Int64)
		case typeconfig.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				tc.Name = value.String
			}
		case typeconfig.FieldRelations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field relations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tc.Relations); err != nil {
					return fmt.Errorf("unmarshal field relations: %w", err)
				}
			}
		case typeconfig.FieldPermissions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field permissions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tc.Permissions); err != nil {
					return fmt.Errorf("unmarshal field permissions: %w", err)
				}
			}
		}
	}
	return nil
}

// Update returns a builder for updating this TypeConfig.
// Note that you need to call TypeConfig.Unwrap() before calling this method if this TypeConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (tc *TypeConfig) Update() *TypeConfigUpdateOne {
	return (&TypeConfigClient{config: tc.config}).UpdateOne(tc)
}

// Unwrap unwraps the TypeConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tc *TypeConfig) Unwrap() *TypeConfig {
	tx, ok := tc.config.driver.(*txDriver)
	if !ok {
		panic("ent: TypeConfig is not a transactional entity")
	}
	tc.config.driver = tx.drv
	return tc
}

// String implements the fmt.Stringer.
func (tc *TypeConfig) String() string {
	var builder strings.Builder
	builder.WriteString("TypeConfig(")
	builder.WriteString(fmt.Sprintf("id=%v", tc.ID))
	builder.WriteString(", name=")
	builder.WriteString(tc.Name)
	builder.WriteString(", relations=")
	builder.WriteString(fmt.Sprintf("%v", tc.Relations))
	builder.WriteString(", permissions=")
	builder.WriteString(fmt.Sprintf("%v", tc.Permissions))
	builder.WriteByte(')')
	return builder.String()
}

// TypeConfigs is a parsable slice of TypeConfig.
type TypeConfigs []*TypeConfig

func (tc TypeConfigs) config(cfg config) {
	for _i := range tc {
		tc[_i].config = cfg
	}
}
