name: Test
on:
  push:
    paths:
      - "**.go"
      - "Dockerfile"
      - "**.yml"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1

      - run: task test

      - name: Build binary
        run: task build

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: kala
          remote_path: /home/ubuntu/kala/
          remote_host: ${{ secrets.IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}

  build-and-scan-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - uses: actions/checkout@v3

      - name: Build the image
        run: docker build -t kala:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: kala:latest
          format: "table"
          exit-code: "0"
          ignore-unfixed: false
          severity: "CRITICAL,HIGH"
